# Time after which the advertising message will be displayed
# Calculated in minutes
adsTime: 15
# Format for displaying advertising messages in chat
adsMessageFormat: "<RGB:1,0.8,0.1> [Реклама]: <SPACE_SYMBOL> <RGB:1,1,1> <TEXT>"
# List of advertising messages
adsMessages:
  - "Увидели читера? Сообщите администрации!"
  - "Пожалуйста, соблюдайте правила сервера"
  - "Присоединяйтесь к нашему сообществу <RGB:1,0.8,0.1> <SPACE_SYMBOL> Discord"
  - "Если у Вас появилась интересная идея по улучшению сервера или заметили баг, сообщите администрации"